### ISSUE TITLE
How to get embedded audio from MKV file?

### ISSUE THREAD

**Issue by WinPhoneDev** [Microsoft/FFmpegInterop#37] opened 2015-10-03 12:33 UTC
Hi, 
Some MKV's file has embedded[multiple] audio, how can we get them as list and the User can pick which on most plays?
Thanks

**Comment by timotiusmargo** [comment] 2015-10-08 22:34
Marking this as duplicate of https://github.com/Microsoft/FFmpegInterop/issues/38

**Closed by timotiusmargo** 2015-10-08 22:34 UTC
Labels: duplicate
